import os
import uuid
import tempfile
import traceback
from typing import Dict, Any, Optional

from fastapi import FastAPI, File, UploadFile, Form, HTTPException
from fastapi.responses import JSONResponse, FileResponse
import uvicorn

from algorithm import process_histology_features

app = FastAPI(
    title="Histology Feature Extraction (stLearn)",
    description="Extract deep-learning morphological features from Visium H&E histological images.",
    version="1.0.0",
)

OUTPUT_DIR = os.getenv("OUTPUT_DIR", "./outputs")
os.makedirs(OUTPUT_DIR, exist_ok=True)

def format_error_info_to_message(error_info: Dict[str, Any]) -> str:
    parts = []
    parts.append(f"Error Type: {error_info.get('error_type', 'Unknown')}")
    parts.append(f"Error Message: {error_info.get('error_message', 'Unknown error')}")
    if "diagnosis" in error_info:
        parts.append(f"\nDiagnosis: {error_info['diagnosis']}")
    if "suggestions" in error_info and error_info["suggestions"]:
        parts.append("\nSuggestions:")
        for idx, suggestion in enumerate(error_info["suggestions"], 1):
            if isinstance(suggestion, dict):
                issue = suggestion.get("issue", "Unknown issue")
                recommendations = suggestion.get("recommendations", [])
                parts.append(f"\n  {idx}. {issue}:")
                for rec in recommendations:
                    parts.append(f"     - {rec}")
    return "\n".join(parts)


def handle_error(step: str, error: Exception, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    error_info = {
        "error": True,
        "step": step,
        "error_type": type(error).__name__,
        "error_message": str(error),
        "suggestions": []
    }
    error_msg_lower = str(error).lower()
    
    if "images" in error_msg_lower or "uns" in error_msg_lower:
        error_info["diagnosis"] = "Missing H&E Image Metadata in AnnData"
        error_info["suggestions"].extend([{
            "issue": "Your input file does not contain spatial histological images",
            "recommendations": [
                "Ensure you uploaded a complete 10X Visium h5ad file generated by SpaceRanger",
                "Ensure 'uns['spatial'][library_id]['images']['hires']' exists within your h5ad"
            ]
        }])
    elif "memory" in error_msg_lower or "cuda" in error_msg_lower or "alloc" in error_msg_lower:
        error_info["diagnosis"] = "GPU/CPU Out of Memory during ResNet50 extraction"
        error_info["suggestions"].extend([{
            "issue": "Insufficient memory available for deep learning image extraction",
            "recommendations": [
                "Switch 'use_gpu' to false if the GPU is fully occupied",
                "Downsample or use lower resolution images ('lowres')"
            ]
        }])
    else:
        error_info["diagnosis"] = "Algorithm execution failed"
        error_info["suggestions"].extend([{
            "issue": "Unknown runtime error during image feature extraction",
            "recommendations": [
                "Check whether spatial coordinates align with the image grid",
                "Ensure your h5ad data matrix is densely/sparsely formatted appropriately"
            ]
        }])
        
    return error_info


@app.post("/api/histology-feature-extraction")
async def execute_histology_extraction(
    file: UploadFile = File(...),
    file_type: str = Form("auto"),
    use_gpu: bool = Form(True),
    cnn_base: str = Form("resnet50"),
    n_components: int = Form(50),
    physical_distance: float = Form(1.0)
) -> JSONResponse:
    temp_input_path = None
    try:
        file_id = str(uuid.uuid4())
        temp_input_path = os.path.join(tempfile.gettempdir(), f"input_{file_id}_{file.filename}")
        
        with open(temp_input_path, "wb") as f:
            content = await file.read()
            f.write(content)
            
        request_id = str(uuid.uuid4())
        
        output_files = process_histology_features(
            adata_path=temp_input_path,
            use_gpu=use_gpu,
            cnn_base=cnn_base,
            n_components=n_components,
            physical_distance=physical_distance,
            output_dir=OUTPUT_DIR
        )
        
        data_dict = {}
        for logical_name, temp_name in output_files.items():
            unique_filename = f"{request_id}_{logical_name}"
            
            old_path = os.path.join(OUTPUT_DIR, temp_name)
            new_path = os.path.join(OUTPUT_DIR, unique_filename)
            if os.path.exists(old_path):
                os.rename(old_path, new_path)
            
            data_dict[logical_name] = unique_filename
            
        return JSONResponse(
            status_code=200,
            content={"success": True, "message": "Histological feature extraction & SME completed successfully.", "data": data_dict},
        )
        
    except Exception as e:
        traceback.print_exc()
        context = {"cnn_base": cnn_base}
        error_info = handle_error("execution_step", e, context=context)
        error_message = format_error_info_to_message(error_info)
        
        return JSONResponse(
            status_code=500,
            content={
                "success": False,
                "message": error_message
            }
        )
    finally:
        if temp_input_path and os.path.exists(temp_input_path):
            try:
                os.remove(temp_input_path)
            except:
                pass


@app.get("/api/download/{file_id}")
async def download_file(file_id: str) -> FileResponse:
    file_path = os.path.join(OUTPUT_DIR, file_id)
    
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail=f"File not found: {file_id}")
        
    if file_path.endswith(".png"):
        media_type = "image/png"
    elif file_path.endswith(".h5ad"):
        media_type = "application/octet-stream"
    elif file_path.endswith(".csv"):
        media_type = "text/csv"
    else:
        media_type = "text/plain"
        
    return FileResponse(path=file_path, filename=file_id, media_type=media_type)

@app.get("/health")
async def health():
    return {"status": "healthy", "output_dir": OUTPUT_DIR}

if __name__ == "__main__":
    port = int(os.getenv("PORT", 53903))
    uvicorn.run(app, host="0.0.0.0", port=port)
