"""
Utility helpers that wrap LLM interactions for the textMSA project.

Notes on optional dependencies:
- We lazily import `langchain_openai.ChatOpenAI` and `langchain_core.messages`
  inside functions. This keeps the module importable in environments where
  these heavy dependencies are not installed, which is useful for unit tests
  that don't exercise LLM calls.
"""

from __future__ import annotations

import json
from typing import Any, Dict, Optional, TYPE_CHECKING

from textmsa.logging_config import get_logger
from textmsa.settings import get_llm_config, ConfigError
from textmsa.utils.json_utils import clean_json_response

if TYPE_CHECKING:  # only for type checkers; avoid hard runtime import
    from langchain_openai import ChatOpenAI  # pragma: no cover

logger = get_logger(__name__)


def create_llm(custom_config: Optional[Dict[str, Any]] = None):
    """
    Instantiate the shared ChatOpenAI client with optional overrides.

    We import ChatOpenAI lazily to keep this module importable without the
    dependency when tests do not exercise LLM calls.
    """
    try:
        from langchain_openai import ChatOpenAI  # type: ignore
    except Exception as exc:  # pragma: no cover - executed only when missing
        raise ConfigError(
            "langchain_openai 未安装，无法创建LLM客户端。请先安装该依赖。"
        ) from exc

    config = {**get_llm_config(), **(custom_config or {})}
    logger.debug(
        "Creating LLM with config: %s",
        {k: v for k, v in config.items() if k != "api_key"},
    )
    return ChatOpenAI(**config)


def call_llm(
    llm,
    system_prompt: str,
    user_prompt: str,
) -> str:
    """
    Execute an LLM call and return the raw textual response.
    """
    try:
        # Lazy import to avoid hard dependency during module import
        from langchain_core.messages import HumanMessage, SystemMessage  # type: ignore
        messages = [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)]
        response = llm.invoke(messages)
        return response.content
    except Exception as exc:  # pragma: no cover - defensive logging
        logger.error("LLM invocation failed: %s", exc)
        return ""


def parse_llm_json_response(
    response_text: str,
    default_value: Optional[Any] = None,
) -> Any:
    """
    Clean and parse JSON content generated by the LLM.
    """
    if not response_text:
        return default_value

    try:
        cleaned = clean_json_response(response_text)
        logger.debug("Cleaned LLM JSON text: %s", cleaned[:200])
        return json.loads(cleaned)
    except json.JSONDecodeError as exc:
        logger.warning("Failed to parse LLM JSON response: %s", exc)
        logger.debug("Original LLM response: %s", response_text)
        return default_value
